name: My Starter Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy to your project.

  call-reusable-workflow:  # This job was correctly placed initially, but it should be unique or restructured.
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      node: 14

  call-reusable-workflow-matrix:  # Renamed job to avoid duplication and conflict
    strategy:
      matrix:
        nodeversion: [14, 16, 18, 20]
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      node: ${{ matrix.nodeversion }}
